alter table if exists colors drop constraint if exists FKodrdh6hgti3581tlu1qhma37l;
alter table if exists deliveries drop constraint if exists FKbx0umi53wgkanvu9vphqnx69l;
alter table if exists orders drop constraint if exists FKm2dep9derpoaehshbkkatam3v;
alter table if exists orders drop constraint if exists FK517vqfpcs3tncyw22i0x7ikbp;
alter table if exists phones drop constraint if exists FK2ovgkw92fjf0rn5yksjxa755b;
alter table if exists product_arrivals drop constraint if exists FKo4ffj8j1nd2tro2tur5hy5lsq;
alter table if exists products drop constraint if exists FKebociq5k3b2tkcxh3q5dg4eed;
alter table if exists products drop constraint if exists FKbxtog86921x3rp4ehfk0t1eiq;
alter table if exists products_in_order drop constraint if exists FK52yge8hl6teqf4n4bkul5k5dm;
alter table if exists products_in_order drop constraint if exists FK60tyehiqoydncbdl4sy6b3tic;
drop table if exists categories cascade;
drop table if exists clients cascade;
drop table if exists colors cascade;
drop table if exists deliveries cascade;
drop table if exists orders cascade;
drop table if exists orders_statuses cascade;
drop table if exists phones cascade;
drop table if exists product_arrivals cascade;
drop table if exists product_photos cascade;
drop table if exists products cascade;
drop table if exists products_in_order cascade;

create table categories (id int8 generated by default as identity, description varchar(255), is_visible boolean not null, name varchar(255), primary key (id));

create table clients (id int8 generated by default as identity, client_type varchar(255), email varchar(255), name varchar(255), note varchar(255), website varchar(255), primary key (id));

create table colors (id int8 generated by default as identity, description varchar(255) not null, is_visible boolean not null, name varchar(255) not null, category_id int8 not null, primary key (id));

create table deliveries (client_id int8 not null, delivery varchar(255));

create table orders (id int8 generated by default as identity, date date, number varchar(255), client_id int8, status_id int8, primary key (id));

create table orders_statuses (id int8 generated by default as identity, color varchar(255), name varchar(255), number int4 not null, primary key (id));

create table phones (client_id int8 not null, phone varchar(255));

create table product_arrivals (id int8 generated by default as identity, count int8 not null, date date not null, number varchar(255) not null, product_id int8, primary key (id));

create table product_photos (id int8 generated by default as identity, file_name varchar(255), primary key (id));

create table products (id int8 generated by default as identity, articul varchar(255) not null, incoming_balance int8 not null, is_visible boolean not null, name varchar(255) not null, price numeric(19, 2) not null, size varchar(255) not null, color_id int8, photo_id int8, primary key (id));

create table products_in_order (id int8 generated by default as identity, count int8, price numeric(19, 2), order_id int8, product_id int8, primary key (id));

alter table if exists colors add constraint FKodrdh6hgti3581tlu1qhma37l foreign key (category_id) references categories;

alter table if exists deliveries add constraint FKbx0umi53wgkanvu9vphqnx69l foreign key (client_id) references clients;

alter table if exists orders add constraint FKm2dep9derpoaehshbkkatam3v foreign key (client_id) references clients;

alter table if exists orders add constraint FK517vqfpcs3tncyw22i0x7ikbp foreign key (status_id) references orders_statuses;

alter table if exists phones add constraint FK2ovgkw92fjf0rn5yksjxa755b foreign key (client_id) references clients;

alter table if exists product_arrivals add constraint FKo4ffj8j1nd2tro2tur5hy5lsq foreign key (product_id) references products;

alter table if exists products add constraint FKebociq5k3b2tkcxh3q5dg4eed foreign key (color_id) references colors;

alter table if exists products add constraint FKbxtog86921x3rp4ehfk0t1eiq foreign key (photo_id) references product_photos;

alter table if exists products_in_order add constraint FK52yge8hl6teqf4n4bkul5k5dm foreign key (order_id) references orders;

alter table if exists products_in_order add constraint FK60tyehiqoydncbdl4sy6b3tic foreign key (product_id) references products;