create table categories (
    id bigint generated by default as identity,
    name varchar(255) not null,
    description varchar(255) not null,
    primary key (id)
);

create table colors (
   id bigint generated by default as identity,
   name varchar(255) not null,
   description varchar(255) not null,
   category_id bigint not null,
   primary key (id)
);

create table products (
    id bigint generated by default as identity,
    articul varchar(255) not null,
    name varchar(255) not null,
    price numeric(19, 2) not null,
    size varchar(255) not null,
    incoming_balance bigint,
    color_id bigint,
    primary key (id)
);



alter table if exists products add constraint UK_2v8n0ybyxk92p5bk1e8ummwyb unique (articul);
alter table if exists colors add constraint FKodrdh6hgti3581tlu1qhma37l foreign key (category_id) references categories;
alter table if exists products add constraint FKebociq5k3b2tkcxh3q5dg4eed foreign key (color_id) references colors;